<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        /*
         * Store the latest overall login information directly
         * against the customer.
         */
        Schema::table('users', function (Blueprint $table) {
            $table->timestamp('last_login_at')
                ->nullable()
                ->after('status');

            $table->string('last_login_ip', 45)
                ->nullable()
                ->after('last_login_at');
        });

        /*
         * Store separate login and notification information
         * for every device used by a customer.
         */
        Schema::create('user_devices', function (Blueprint $table) {
            $table->id();

            $table->foreignId('user_id')
                ->constrained('users')
                ->cascadeOnDelete();

            /*
             * The Sanctum personal_access_tokens table ID.
             *
             * This connects one app login token with one device.
             */
            $table->unsignedBigInteger('sanctum_token_id')
                ->nullable()
                ->index();

            /*
             * Stable device/application installation identifier
             * generated by the mobile application.
             */
            $table->string('device_id', 255);

            /*
             * Firebase Cloud Messaging token.
             *
             * Text is used because notification tokens may be long.
             */
            $table->text('fcm_token')->nullable();

            /*
             * Hash allows efficient token matching without indexing
             * the complete long FCM token.
             */
            $table->char('fcm_token_hash', 64)
                ->nullable()
                ->index();

            $table->string('device_name')->nullable();
            $table->string('device_model')->nullable();

            $table->string('platform', 20)->nullable();
            $table->string('os_version', 50)->nullable();
            $table->string('app_version', 50)->nullable();

            $table->string('timezone', 100)->nullable();
            $table->string('locale', 20)->nullable();

            $table->string('last_ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();

            $table->boolean('notifications_enabled')
                ->default(true);

            $table->boolean('is_active')
                ->default(true);

            $table->timestamp('logged_in_at')->nullable();
            $table->timestamp('last_seen_at')->nullable();
            $table->timestamp('logged_out_at')->nullable();

            $table->timestamps();

            /*
             * One device can have only one record per user.
             */
            $table->unique(
                ['user_id', 'device_id'],
                'user_devices_user_device_unique'
            );

            $table->index(
                ['user_id', 'is_active', 'notifications_enabled'],
                'user_devices_notification_index'
            );
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('user_devices');

        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn([
                'last_login_at',
                'last_login_ip',
            ]);
        });
    }
};