@extends('website.layouts.app')
@section('title', 'About Fulawala')
@section('meta_description', 'Learn about Fulawala, our commitment to fresh flowers, convenient pooja supplies and thoughtful floral services.')
@section('content')
@include('website.partials.page-hero', ['title'=>'About Fulawala','eyebrow'=>'Our story','description'=>'A modern flower service rooted in freshness, devotion and thoughtful celebrations.'])
<section class="section"><div class="container story-grid"><div class="story-art reveal-on-scroll"><img src="{{ asset('website/images/about-floral.svg') }}" alt="Fulawala flower story"><div class="story-stat"><strong>Everyday</strong><span>freshness and care</span></div></div><div class="story-copy reveal-on-scroll"><span class="eyebrow">Flowers connect people, prayer and celebration</span><h2>Making beautiful traditions easier for modern families</h2><p>Fulawala was created to make fresh flowers and pooja essentials easier to access. We bring together careful selection, convenient ordering, flexible delivery and personalised support.</p><p>Whether it is a quiet morning prayer, a festival, a gift or a grand celebration, our goal is simple: provide fresh flowers and dependable service that respect the importance of your moment.</p><div class="signature-line"><span></span><strong>Team Fulawala</strong></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">What guides us</span><h2>Our values</h2></div><div class="value-grid"><article class="value-card reveal-on-scroll"><div>🌱</div><h3>Freshness</h3><p>Careful sourcing, selection and packing for flowers that feel fresh and presentable.</p></article><article class="value-card reveal-on-scroll"><div>🤝</div><h3>Trust</h3><p>Clear communication and dependable service are at the centre of every order.</p></article><article class="value-card reveal-on-scroll"><div>🪔</div><h3>Respect</h3><p>We understand the devotional and emotional value attached to flowers and rituals.</p></article><article class="value-card reveal-on-scroll"><div>✨</div><h3>Creativity</h3><p>We turn event ideas into elegant floral experiences suited to each occasion.</p></article></div></div></section>
<section class="section"><div class="container mission-grid"><div class="mission-card dark-card reveal-on-scroll"><span class="eyebrow light">Our mission</span><h2>Deliver freshness with convenience and care.</h2><p>To help households, temples, workplaces and event customers access reliable flower services through simple technology and local support.</p></div><div class="mission-card light-card reveal-on-scroll"><span class="eyebrow">Our vision</span><h2>Become a trusted flower partner for everyday India.</h2><p>We aim to build an organised, transparent and customer-friendly flower ecosystem that supports local supply and meaningful traditions.</p></div></div></section>
<section class="section timeline-section"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">How we serve</span><h2>From your requirement to your doorstep</h2></div><div class="process-line"><div class="process-item reveal-on-scroll"><span>1</span><h3>Understand</h3><p>We confirm flowers, quantity, date, location and instructions.</p></div><div class="process-item reveal-on-scroll"><span>2</span><h3>Prepare</h3><p>Your order is selected, sorted and packed carefully.</p></div><div class="process-item reveal-on-scroll"><span>3</span><h3>Deliver</h3><p>The order reaches the agreed location and schedule.</p></div><div class="process-item reveal-on-scroll"><span>4</span><h3>Support</h3><p>Our team remains available for future requirements.</p></div></div></div></section>
<section class="cta-band"><div class="container cta-band-inner reveal-on-scroll"><div><span class="eyebrow light">Start with Fulawala</span><h2>Fresh flowers are only a message away.</h2></div><a href="{{ route('website.contact') }}" class="btn btn-light">Contact Our Team <span>→</span></a></div></section>
@endsection
