@extends('website.layouts.app')
@section('title', 'Floral Event Decoration')
@section('meta_description', 'Plan wedding, birthday, puja and corporate floral decoration with Fulawala.')
@section('content')
@include('website.partials.page-hero', ['title'=>'Event Decoration','eyebrow'=>'Celebrate beautifully','description'=>'Personalised floral styling for weddings, birthdays, pujas, inaugurations and corporate occasions.'])
<section class="section"><div class="container event-intro-grid"><div class="reveal-on-scroll"><span class="eyebrow">Designed around your story</span><h2>From a simple floral corner to a complete venue theme</h2><p>Our decoration service is planned according to your occasion, venue, colour preference, traditions and budget. We focus on balanced design, clean execution and a beautiful guest experience.</p><a href="{{ route('website.contact', ['service'=>'Event Decoration']) }}" class="btn btn-primary">Request a Quotation <span>→</span></a></div><div class="reveal-on-scroll"><img src="{{ asset('website/images/event-decoration.svg') }}" alt="Fulawala event decoration"></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">Occasions we decorate</span><h2>Floral experiences for every celebration</h2></div><div class="occasion-grid"><article class="occasion-card reveal-on-scroll"><span>💍</span><h3>Weddings</h3><p>Mandap, entrance, stage, varmala, car and room decoration.</p></article><article class="occasion-card reveal-on-scroll"><span>🎂</span><h3>Birthdays</h3><p>Backdrops, table flowers, entrance styling and photo corners.</p></article><article class="occasion-card reveal-on-scroll"><span>🪔</span><h3>Puja & Festivals</h3><p>Traditional decoration for home, temple and community rituals.</p></article><article class="occasion-card reveal-on-scroll"><span>🏢</span><h3>Corporate Events</h3><p>Professional stage, reception, inauguration and conference florals.</p></article><article class="occasion-card reveal-on-scroll"><span>🏡</span><h3>Housewarming</h3><p>Doorway, puja area and interior flowers with a welcoming theme.</p></article><article class="occasion-card reveal-on-scroll"><span>🎁</span><h3>Custom Celebrations</h3><p>Concepts for anniversaries, proposals and family functions.</p></article></div></div></section>
<section class="section"><div class="container"><div class="section-heading split-heading reveal-on-scroll"><div><span class="eyebrow">Our process</span><h2>Clear planning, beautiful execution</h2></div><a href="{{ route('website.gallery') }}" class="text-link large">View gallery →</a></div><div class="event-process-grid"><div class="event-process-card reveal-on-scroll"><strong>01</strong><h3>Requirement call</h3><p>We understand event type, date, venue, guest size and preferences.</p></div><div class="event-process-card reveal-on-scroll"><strong>02</strong><h3>Concept & quotation</h3><p>We suggest suitable styles and provide a clear quotation.</p></div><div class="event-process-card reveal-on-scroll"><strong>03</strong><h3>Preparation</h3><p>Flowers, materials and team schedule are organised.</p></div><div class="event-process-card reveal-on-scroll"><strong>04</strong><h3>Installation</h3><p>Our team completes decoration and checks presentation.</p></div></div></div></section>
<section class="section event-enquiry-section"><div class="container event-enquiry-grid"><div class="event-enquiry-copy reveal-on-scroll"><span class="eyebrow light">Plan your event</span><h2>Share your date, venue and idea.</h2><p>Our team will contact you and prepare a suitable proposal.</p><ul class="check-list light-list"><li>Custom concept support</li><li>Transparent quotation</li><li>Venue-specific planning</li><li>Professional setup team</li></ul></div><div class="reveal-on-scroll">@include('website.partials.contact-form')</div></div></section>
@endsection
