@extends('website.layouts.app')
@section('title', 'Fresh Flowers')
@section('meta_description', 'Browse fresh flowers for pooja, gifting, decoration and everyday use from Fulawala.')
@section('content')
@include('website.partials.page-hero', ['title'=>'Fresh Flowers','eyebrow'=>'Freshly selected','description'=>'Beautiful flowers for worship, gifting, home decoration and every meaningful moment.'])
<section class="section catalog-section"><div class="container"><div class="catalog-toolbar reveal-on-scroll"><div><h2>Explore our collection</h2><p>Availability and pricing may vary by season and delivery area.</p></div><form method="GET" action="{{ route('website.flowers') }}" class="search-form"><input type="search" name="search" value="{{ request('search') }}" placeholder="Search flowers..." aria-label="Search flowers"><button type="submit">Search</button></form></div>
@if($flowers->isNotEmpty())<div class="product-grid">@foreach($flowers as $flower)@include('website.partials.product-card', ['item'=>$flower,'type'=>'flower'])@endforeach</div>@if(method_exists($flowers,'links')){{ $flowers->links('website.pagination.fulawala') }}@endif
@else @php($fallback=collect([(object)['name'=>'Marigold Flowers','description'=>'Traditional bright flowers for daily pooja, festivals and decoration.','price'=>80],(object)['name'=>'Fresh Roses','description'=>'Classic roses for gifting and special occasions.','price'=>120],(object)['name'=>'Jasmine Flowers','description'=>'Fragrant jasmine suitable for pooja and traditional use.','price'=>100],(object)['name'=>'Lotus Flowers','description'=>'Sacred lotus offered according to seasonal availability.','price'=>150],(object)['name'=>'Mixed Pooja Flowers','description'=>'A balanced selection for everyday worship.','price'=>90],(object)['name'=>'Flower Garland','description'=>'Freshly prepared garlands for deities and ceremonies.','price'=>180]]))
@if(request('search'))<div class="empty-state"><span>🌼</span><h3>No flowers found</h3><p>Try another search or contact us for availability.</p><a href="{{ route('website.flowers') }}" class="btn btn-secondary">Clear Search</a></div>@else<div class="product-grid">@foreach($fallback as $flower)@include('website.partials.product-card', ['item'=>$flower,'type'=>'flower'])@endforeach</div>@endif @endif
</div></section>
<section class="section section-soft flower-care-section"><div class="container flower-care-grid"><div class="reveal-on-scroll"><span class="eyebrow">Keep them fresh</span><h2>Simple flower care tips</h2><p>Fresh flowers naturally last longer when handled carefully after delivery.</p></div><div class="care-list"><div class="care-item reveal-on-scroll"><span>01</span><p>Keep flowers in a cool, shaded area away from direct sunlight.</p></div><div class="care-item reveal-on-scroll"><span>02</span><p>Use clean water and a clean container for loose flowers or stems.</p></div><div class="care-item reveal-on-scroll"><span>03</span><p>Use pooja flowers early for the best freshness and fragrance.</p></div></div></div></section>
@endsection
