@extends('website.layouts.app')
@section('title', 'Fresh Flowers, Pooja Packets & Event Decoration')
@section('meta_description', 'Order fresh flowers, pooja packets, subscriptions and floral event decoration from Fulawala.')
@section('content')
<section class="hero-section">
    <div class="hero-pattern"></div>
    <div class="container hero-grid">
        <div class="hero-copy reveal-on-scroll">
            <div class="hero-rating"><span>★★★★★</span> Freshness you can trust</div>
            <span class="eyebrow">Flowers for every sacred and special moment</span>
            <h1>Fresh flowers.<br><em>Beautiful moments.</em></h1>
            <p>{{ config('website.tagline') }} From everyday pooja to unforgettable celebrations, Fulawala brings freshness to your doorstep.</p>
            <div class="hero-actions"><a href="{{ route('website.flowers') }}" class="btn btn-primary">Explore Flowers <span>→</span></a><a href="{{ route('website.subscriptions') }}" class="btn btn-secondary">View Subscriptions</a></div>
            <div class="hero-trust-row"><div><strong>Fresh</strong><span>Handpicked flowers</span></div><div><strong>Flexible</strong><span>Delivery schedules</span></div><div><strong>Careful</strong><span>Hygienic packing</span></div></div>
        </div>
        <div class="hero-visual reveal-on-scroll">
            <div class="hero-image-card"><img src="{{ asset('website/images/hero-bouquet.svg') }}" alt="Colourful flower bouquet"><div class="floating-card card-top"><span class="floating-icon">🌿</span><div><strong>Farm fresh</strong><small>Carefully selected</small></div></div><div class="floating-card card-bottom"><span class="floating-icon">🚚</span><div><strong>Doorstep delivery</strong><small>At your preferred time</small></div></div></div>
        </div>
    </div>
</section>

<section class="section section-soft"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">Everything floral, one trusted place</span><h2>Made for your everyday rituals and celebrations</h2><p>Choose fresh flowers, ready pooja packets, convenient subscriptions and personalised event decoration.</p></div><div class="service-grid">@foreach($services as $service)<a href="{{ route($service['route']) }}" class="service-card reveal-on-scroll"><span class="service-icon">{{ $service['icon'] }}</span><h3>{{ $service['title'] }}</h3><p>{{ $service['description'] }}</p><span class="text-link">Learn more →</span></a>@endforeach</div></div></section>

<section class="section"><div class="container"><div class="section-heading split-heading reveal-on-scroll"><div><span class="eyebrow">Fresh picks</span><h2>Popular flowers</h2></div><a href="{{ route('website.flowers') }}" class="text-link large">View all flowers →</a></div>
@if($featuredFlowers->isNotEmpty())<div class="product-grid">@foreach($featuredFlowers as $flower)@include('website.partials.product-card', ['item'=>$flower,'type'=>'flower'])@endforeach</div>
@else @php($fallbackFlowers=collect([(object)['name'=>'Fresh Marigold','description'=>'Bright flowers for daily worship and decoration.','price'=>80],(object)['name'=>'Rose Collection','description'=>'Elegant roses for gifting, pooja and celebrations.','price'=>120],(object)['name'=>'Jasmine Flowers','description'=>'Naturally fragrant jasmine for prayer and traditional use.','price'=>100],(object)['name'=>'Mixed Pooja Flowers','description'=>'A colourful selection prepared for daily rituals.','price'=>90]]))<div class="product-grid">@foreach($fallbackFlowers as $flower)@include('website.partials.product-card', ['item'=>$flower,'type'=>'flower'])@endforeach</div>@endif
</div></section>

<section class="section pooja-feature-section"><div class="container pooja-feature-grid"><div class="pooja-feature-art reveal-on-scroll"><img src="{{ asset('website/images/pooja-basket.svg') }}" alt="Pooja flower basket"><div class="decorative-ring ring-one"></div><div class="decorative-ring ring-two"></div></div><div class="pooja-feature-copy reveal-on-scroll"><span class="eyebrow light">Prepared with devotion</span><h2>Daily pooja made simple</h2><p>Receive clean, fresh and neatly packed flowers and pooja essentials without the early-morning rush.</p><ul class="check-list light-list"><li>Fresh flowers selected for worship</li><li>Daily, weekly and monthly options</li><li>Convenient doorstep delivery</li><li>Custom packet requirements accepted</li></ul><a href="{{ route('website.pooja-packets') }}" class="btn btn-light">Explore Pooja Packets <span>→</span></a></div></div></section>

<section class="section"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">Simple subscriptions</span><h2>Freshness on your schedule</h2><p>Set your plan once and enjoy dependable delivery for your home, temple or workplace.</p></div><div class="steps-grid"><div class="step-card reveal-on-scroll"><span>01</span><div class="step-icon">🌺</div><h3>Choose flowers</h3><p>Select the packet or flower combination that suits your ritual.</p></div><div class="step-card reveal-on-scroll"><span>02</span><div class="step-icon">🗓️</div><h3>Select schedule</h3><p>Pick daily, weekly or monthly delivery and your preferred time slot.</p></div><div class="step-card reveal-on-scroll"><span>03</span><div class="step-icon">🏡</div><h3>Receive at home</h3><p>Get neatly packed fresh flowers delivered to your doorstep.</p></div></div><div class="center-action reveal-on-scroll"><a href="{{ route('website.subscriptions') }}" class="btn btn-primary">See Subscription Plans <span>→</span></a></div></div></section>

<section class="section event-showcase-section"><div class="container event-showcase-grid"><div class="event-copy reveal-on-scroll"><span class="eyebrow">Celebrate beautifully</span><h2>Floral decoration designed around your occasion</h2><p>From intimate family pujas to weddings and corporate events, our team creates elegant floral experiences according to your venue, theme and budget.</p><div class="mini-feature-grid"><div><strong>Wedding</strong><span>Mandap, entrance and stage flowers</span></div><div><strong>Puja</strong><span>Traditional and devotional decoration</span></div><div><strong>Birthday</strong><span>Modern flower and balloon themes</span></div><div><strong>Corporate</strong><span>Professional floral styling</span></div></div><a href="{{ route('website.events') }}" class="btn btn-primary">Plan Your Event <span>→</span></a></div><div class="event-art reveal-on-scroll"><img src="{{ asset('website/images/event-decoration.svg') }}" alt="Floral event decoration"></div></div></section>

<section class="section section-soft"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">Why Fulawala</span><h2>Thoughtful service from selection to delivery</h2></div><div class="benefit-grid"><div class="benefit-card reveal-on-scroll"><span>01</span><h3>Freshness first</h3><p>Flowers are selected carefully and packed to preserve their natural beauty.</p></div><div class="benefit-card reveal-on-scroll"><span>02</span><h3>Reliable delivery</h3><p>Flexible delivery options make daily worship and events easier to manage.</p></div><div class="benefit-card reveal-on-scroll"><span>03</span><h3>Custom support</h3><p>Our team helps with special packets, quantities, themes and event requirements.</p></div><div class="benefit-card reveal-on-scroll"><span>04</span><h3>Local understanding</h3><p>Services are designed for local traditions, festivals and everyday needs.</p></div></div></div></section>

<section class="section testimonials-section"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">Customer stories</span><h2>Fresh flowers, happy moments</h2></div><div class="testimonial-grid">@foreach($testimonials as $testimonial)<article class="testimonial-card reveal-on-scroll"><div class="quote-mark">“</div><div class="stars">★★★★★</div><p>{{ $testimonial['quote'] }}</p><div class="testimonial-user"><span>{{ strtoupper(substr($testimonial['name'],0,1)) }}</span><div><strong>{{ $testimonial['name'] }}</strong><small>{{ $testimonial['role'] }}</small></div></div></article>@endforeach</div></div></section>

<section class="section faq-section"><div class="container faq-grid-layout"><div class="faq-intro reveal-on-scroll"><span class="eyebrow">Questions answered</span><h2>Everything you need to know</h2><p>Need help choosing a service? Contact our team and we will guide you.</p><a href="{{ route('website.contact') }}" class="btn btn-secondary">Contact Fulawala</a></div><div class="faq-list">@foreach($faqs as $index=>$faq)<div class="faq-item reveal-on-scroll {{ $index===0?'open':'' }}"><button type="button" class="faq-question" aria-expanded="{{ $index===0?'true':'false' }}"><span>{{ $faq['question'] }}</span><span class="faq-symbol">+</span></button><div class="faq-answer"><p>{{ $faq['answer'] }}</p></div></div>@endforeach</div></div></section>

<section class="cta-band"><div class="container cta-band-inner reveal-on-scroll"><div><span class="eyebrow light">Let flowers make it special</span><h2>Tell us what you need. We will prepare it with care.</h2></div><a href="{{ route('website.contact') }}" class="btn btn-light">Send an Enquiry <span>→</span></a></div></section>
@endsection
