@extends('website.layouts.app')
@section('title', 'Pooja Flower Packets')
@section('meta_description', 'Discover Fulawala pooja flower packets and flexible daily, weekly and monthly worship flower plans.')
@section('content')
@include('website.partials.page-hero', ['title'=>'Pooja Packets','eyebrow'=>'Prepared for worship','description'=>'Fresh flowers and convenient pooja combinations prepared for daily and special rituals.'])
<section class="section catalog-section"><div class="container"><div class="catalog-toolbar reveal-on-scroll"><div><h2>Choose your pooja packet</h2><p>Packet contents can be customised according to availability and requirement.</p></div><form method="GET" action="{{ route('website.pooja-packets') }}" class="search-form"><input type="search" name="search" value="{{ request('search') }}" placeholder="Search packets..." aria-label="Search pooja packets"><button type="submit">Search</button></form></div>
@if($packets->isNotEmpty())<div class="product-grid">@foreach($packets as $packet)@include('website.partials.product-card', ['item'=>$packet,'type'=>'packet'])@endforeach</div>@if(method_exists($packets,'links')){{ $packets->links('website.pagination.fulawala') }}@endif
@else @php($fallback=collect([(object)['packet_name'=>'Daily Pooja Packet','description'=>'Fresh mixed flowers for regular morning worship.','sale_price'=>50,'package_type'=>'Daily'],(object)['packet_name'=>'Weekly Devotion Pack','description'=>'A convenient weekly plan for consistent pooja flower needs.','sale_price'=>299,'package_type'=>'Weekly'],(object)['packet_name'=>'Monthly Flower Plan','description'=>'Scheduled daily flower delivery throughout the month.','sale_price'=>999,'package_type'=>'Monthly'],(object)['packet_name'=>'Festival Special Packet','description'=>'A fuller flower selection for festivals and special pujas.','sale_price'=>199,'package_type'=>'Special']]))
@if(request('search'))<div class="empty-state"><span>🪔</span><h3>No packets found</h3><p>Try another search or send us your custom requirement.</p><a href="{{ route('website.pooja-packets') }}" class="btn btn-secondary">Clear Search</a></div>@else<div class="product-grid">@foreach($fallback as $packet)@include('website.partials.product-card', ['item'=>$packet,'type'=>'packet'])@endforeach</div>@endif @endif
</div></section>
<section class="section pooja-includes-section"><div class="container pooja-includes-grid"><div class="reveal-on-scroll"><img src="{{ asset('website/images/pooja-basket.svg') }}" alt="Pooja packet contents"></div><div class="reveal-on-scroll"><span class="eyebrow">Designed around your ritual</span><h2>What can be included?</h2><p>Contents depend on your selected packet, local tradition, season and availability.</p><div class="chip-list"><span>Marigold</span><span>Rose</span><span>Jasmine</span><span>Lotus</span><span>Leaves</span><span>Garland</span><span>Custom flowers</span></div><a href="{{ route('website.contact', ['service'=>'Custom Pooja Packet']) }}" class="btn btn-primary">Request Custom Packet <span>→</span></a></div></div></section>
@endsection
