@extends('website.layouts.app')
@section('title', 'Flower Subscription Plans')
@section('meta_description', 'Choose daily, weekly or monthly Fulawala flower subscriptions for home, temple or workplace delivery.')
@section('content')
@include('website.partials.page-hero', ['title'=>'Flower Subscriptions','eyebrow'=>'Fresh flowers on schedule','description'=>'Choose a plan once and receive fresh flowers at your preferred frequency.'])
<section class="section"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">Flexible plans</span><h2>A subscription for every routine</h2><p>Pricing is finalised according to flower type, quantity, delivery area and schedule.</p></div><div class="pricing-grid">
<article class="pricing-card reveal-on-scroll"><div class="pricing-icon">☀️</div><span class="plan-label">Daily</span><h3>Daily Devotion</h3><p>Best for households and temples requiring fresh flowers every morning.</p><ul class="check-list"><li>Daily scheduled delivery</li><li>Flexible flower combination</li><li>Pause or update plan</li><li>Doorstep convenience</li></ul><a href="{{ route('website.contact', ['service'=>'Daily Flower Subscription']) }}" class="btn btn-secondary btn-full">Ask for Pricing</a></article>
<article class="pricing-card featured reveal-on-scroll"><div class="popular-label">Most Popular</div><div class="pricing-icon">🌸</div><span class="plan-label">Weekly</span><h3>Weekly Freshness</h3><p>A balanced plan for weekly pooja, home decoration or workplace use.</p><ul class="check-list"><li>Choose delivery days</li><li>Custom quantity options</li><li>Priority support</li><li>Easy renewal</li></ul><a href="{{ route('website.contact', ['service'=>'Weekly Flower Subscription']) }}" class="btn btn-primary btn-full">Choose Weekly Plan</a></article>
<article class="pricing-card reveal-on-scroll"><div class="pricing-icon">🗓️</div><span class="plan-label">Monthly</span><h3>Monthly Convenience</h3><p>Plan an entire month of flower deliveries with less daily coordination.</p><ul class="check-list"><li>Monthly schedule planning</li><li>Value-based package</li><li>Festival adjustments</li><li>Delivery reminders</li></ul><a href="{{ route('website.contact', ['service'=>'Monthly Flower Subscription']) }}" class="btn btn-secondary btn-full">Ask for Pricing</a></article>
</div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading centered reveal-on-scroll"><span class="eyebrow">How it works</span><h2>Start in four simple steps</h2></div><div class="process-line compact-process"><div class="process-item reveal-on-scroll"><span>1</span><h3>Share requirement</h3><p>Tell us the flower, quantity and purpose.</p></div><div class="process-item reveal-on-scroll"><span>2</span><h3>Choose frequency</h3><p>Select daily, weekly or monthly delivery.</p></div><div class="process-item reveal-on-scroll"><span>3</span><h3>Confirm schedule</h3><p>Set address, date and preferred time.</p></div><div class="process-item reveal-on-scroll"><span>4</span><h3>Enjoy delivery</h3><p>Receive fresh flowers without repeated ordering.</p></div></div></div></section>
<section class="section"><div class="container subscription-benefit-grid"><div class="reveal-on-scroll"><img src="{{ asset('website/images/delivery.svg') }}" alt="Fulawala flower delivery"></div><div class="reveal-on-scroll"><span class="eyebrow">Built for convenience</span><h2>More than regular delivery</h2><p>A subscription helps you plan flower needs, reduce last-minute buying and maintain a consistent routine.</p><ul class="check-list"><li>Suitable for homes, temples and offices</li><li>Custom quantities for different days</li><li>Festival and special-day adjustments</li><li>Support for pauses and address updates</li></ul><a href="{{ route('website.contact', ['service'=>'Flower Subscription']) }}" class="btn btn-primary">Create My Plan <span>→</span></a></div></div></section>
@endsection
